config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "grams#index"
  resources :grams, except: :index do
    resources :comments, only: :create
  end
  get "grams/:gram_id/comments" => redirect("grams/%{gram_id}")

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :gram, inverse_of: :comments
  belongs_to :user, inverse_of: :comments

  validates :message, presence: true
end

app/models/gram.rb
class Gram < ActiveRecord::Base
  belongs_to :user, inverse_of: :grams
  has_many :comments, inverse_of: :gram, dependent: :destroy
  mount_uploader :image, ImageUploader

  validates :message, presence: true
  validates :image, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are: :confirmable, :lockable, and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :timeoutable

  has_many :grams, inverse_of: :user, dependent: :destroy
  has_many :comments, inverse_of: :user, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :store_location

  # Store the previous URL as a user browses around and redirect to it after a sign in or sign up
  private
  def store_location
    session[:previous_path] = request.fullpath unless request.fullpath.include?("/users") || !request.get?
  end

  def after_sign_in_path_for(resource_or_scope)
    session[:previous_path] || root_path
  end

  def after_sign_up_path_for(resource_or_scope)
    session[:previous_path] || root_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @gram = Gram.find params[:gram_id]
    @comment = Comment.new comment_params.merge(user_id: current_user.id, gram_id: @gram.id)
    if @comment.save
      redirect_to gram_path(@gram)
    else
      @gram_comments = @gram.comments
      render "grams/show", status: :unprocessable_entity
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:message)
  end
end

app/controllers/grams_controller.rb
class GramsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_for_gram_owner, only: [:edit, :update, :destroy]

  def index
    @grams = Gram.all
  end

  def show
    @gram = Gram.find params[:id]
    @comment = Comment.new
    @gram_comments = @gram.comments
  end

  def new
    @gram = Gram.new
  end

  def create
    @gram = Gram.new gram_params.merge(user_id: current_user.id)
    if @gram.save
      redirect_to root_path
    else
      render "new", status: :unprocessable_entity
    end
  end

  def edit
    @gram = Gram.find params[:id]
  end

  def update
    @gram = Gram.find params[:id]
    if @gram.update_attributes gram_params
      redirect_to gram_path(@gram)
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def destroy
    Gram.find(params[:id]).destroy
    redirect_to root_path
  end

  private
  def gram_params
    params.require(:gram).permit(:message, :image)
  end

  def check_for_gram_owner
    render text: "Forbidden: This can only be done by the creator of the gram.", status: :forbidden if current_user != Gram.find(params[:id]).user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/grams_helper.rb
module GramsHelper
end

app/views/grams/edit.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1 box">
			<h2>Edit Your Gram</h2>
			<br>
			<%= simple_form_for @gram do |f| %>
				<%= f.input :message %>
				<%= f.input :image, label: "Image (To keep the current image, leave this field blank)" %>
				<br>
				<%= f.submit "Update", class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
</div>

app/views/grams/index.html.erb
<div class="container-fluid">
	<% @grams.each do |gram| %>
		<div class="row">
			<%= link_to gram_path(gram) do %>
				<div class="col-xs-10 col-xs-offset-1 box">
					<div class="user-handle"><%= gram.user.email %></div>
					<%= image_tag gram.image, class: "img-responsive" %>
					<br>
					<div class="text-center gram-message"><%= gram.message %></div>
				</div>
			<% end %>
		</div>
		<br>
	<% end %>
</div>

app/views/grams/new.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1 box">
			<h2>Create Your Gram</h2>
			<br>
			<%= simple_form_for @gram do |f| %>
				<%= f.input :message %>
				<%= f.input :image %>
				<br>
				<%= f.submit "Post", class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
</div>

app/views/grams/show.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1 box">
			<span class="user-handle"><%= @gram.user.email %></span>
			<% if current_user && current_user == @gram.user %>
				<br class="hidden-br">
				<div class="gram-changes">
					<%= link_to "Edit Gram", edit_gram_path(@gram), class: "btn btn-primary" %>
					<%= link_to "Delete", gram_path(@gram), method: :delete, class: "btn btn-primary", data: {confirm: "Are you sure you want to delete this gram?"} %>
				</div>
				<div class="clearfix"></div>
			<% end %>
			<%= image_tag @gram.image, class: "img-responsive" %>
			<br>
			<div class="text-center gram-message"><%= @gram.message %></div>
		</div>
	</div>
	<br>
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1 box">
			<h3>Add Comment</h3>
			<br>
			<%= simple_form_for [@gram, @comment] do |f| %>
				<%= f.input :message %>
				<%= f.submit "Post", class: "btn btn-primary" %>
			<% end %>
			<% if @gram_comments.present? %>
				<hr>
				<h3>Comments</h3>
				<% @gram_comments.each do |comment| %>
					<blockquote>
						<%= comment.message %>
						<small><%= comment.user.email %></small>
					</blockquote>
				<% end %>
			<% end %>
		</div>
	</div>
	<br>
</div>

app/views/layouts/_devise.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-6 col-xs-offset-3 col-sm-4 col-sm-offset-4 box">
			<%= yield %>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Grammable</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet" type="text/css">
		<link href='https://fonts.googleapis.com/css?family=Josefin+Sans' rel='stylesheet' type='text/css'>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<meta name="viewport" content="width=device-width">
	</head>
	<body>
		<nav class="navbar navbar-inverse">
			<div class="container-fluid">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<%= link_to "Grammable", root_path, class: "navbar-brand" %>
				</div>

				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li><%= link_to "Add Gram", new_gram_path %></li>
					</ul>
					<ul class="nav navbar-nav navbar-right">
						<% if current_user %>
							<li><%= link_to "Sign Out (#{current_user.email})", destroy_user_session_path, method: :delete %></li>
						<% else %>
							<li><%= link_to "Sign In", new_user_session_path %></li>
							<li><%= link_to "Sign Up", new_user_registration_path %></li>
						<% end %>
					</ul>
				</div>
			</div>
		</nav>

		<div class="container-fluid text-center"> 
			<% if flash[:alert] %>
				<span class="alert alert-danger" role="alert"><%= flash[:alert] %></span>
			<% end %>
			<% if flash[:notice] %>
				<span class="alert alert-info" role="alert"><%= flash[:notice] %></span>
			<% end %>
		</div>

		<%= controller.class.name.include?("Devise") ? render("layouts/devise") : yield %>

	</body>
</html>